name: Flutter CI

on: [push, pull_request]

jobs:
  lint:
    name: "Static code analysis"
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - name: Lint analysis
      run: flutter analyze

  build-android:
    name: "Build Android apk"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get

    - name: Build Pandemia APK
      run: flutter build apk
        
  build-iOS:
    name: Build iOS package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: build iOS Pandemia package
        run: flutter build ios --release --no-codesign